version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-container
    networks:
      - postgres-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your-local-db-name
      POSTGRES_USER: your-local-db-user
      POSTGRES_PASSWORD: your-local-db-password

networks:
  postgres-net:
