version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-container
    networks:
      - postgres-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: root_replace
      POSTGRES_PASSWORD: root_replace

networks:
  postgres-net:
