services:
  db:
    image: ankane/pgvector
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web1: 
    build: ./biz 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./biz:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=project1_db
      - DJANGO_DB_USER=project1_user
      - DJANGO_DB_PASSWORD=project1_password
    depends_on:
      - db
  web2: 
    build: ./gpumicro  
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./project2:/gpumicro
    ports:
      - "8001:8000"
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=project2_db
      - DJANGO_DB_USER=project2_user
      - DJANGO_DB_PASSWORD=project2_password
    depends_on:
      - db
