# Generated by Django 3.2.20 on 2023-09-01 19:34

from django.db import migrations, models
import django.db.models.deletion
from pgvector.django import VectorExtension
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_path', models.CharField(max_length=255)),
                ('processed', models.BooleanField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('paragraph_num', models.IntegerField()),
                ('sentence_pos', models.IntegerField()),
                ('sentence_text', models.CharField(max_length=255)),
                ('sentence_embed', pgvector.django.VectorField(dimensions=384)),
                ('idx_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.fileupload')),
            ],
        ),
    ]
