# Generated by Django 3.2.21 on 2023-09-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
