# Generated by Django 3.2.21 on 2023-09-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0003_auto_20230905_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='sentence_text',
            field=models.TextField(),
        ),
    ]
